server:
  port: 8089

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33444432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        linger.ms: 1
    consumer:
      group-id: livechatGroup
      enable-auto-commit: false
      auto-commit-interval: 1s
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      fetch-min-size: 1
      fetch-max-wait: 500
      max-poll-records: 500
    listener:
      concurrency: 1
      ack-mode: manual_immediate
      missing-topics-fatal: false